// Generated by dts-bundle v0.7.3
// Dependencies for this module:
//   ../@utkusarioglu/settings
//   ../@utkusarioglu/settings/t_settings

declare module '@utkusarioglu/settings-fs' {
    export { M_Settings } from "@utkusarioglu/settings";
    export { M_SettingsFs } from "@utkusarioglu/settings-fs/m_settings_fs";
    export { t_settingsStack } from "@utkusarioglu/settings";
}

declare module '@utkusarioglu/settings-fs/m_settings_fs' {
    import { M_Settings } from "@utkusarioglu/settings";
    import { t_filename, t_relativeDirectory } from "@utkusarioglu/settings/t_settings";
    export interface M_SettingsFs extends M_Settings {
    }
    const M_SettingsFs_base: any;
    export abstract class M_SettingsFs extends M_SettingsFs_base {
        protected read_set_AllSettingsFromFile(config_file_relative_directory: t_relativeDirectory, config_filename: t_filename): this;
    }
    export {};
}

